format_version: 3
pipelines:  
  jr-java-quickstart:
    lock_behavior: lockOnFailure
    group: Application
    materials:
      repo:
        git: https://github.com/devops-at06/JR.git
        branch: master
    stages:
      - Build:
          jobs:
            building:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "quickstart/"
              artifacts:
                - build:
                    source: quickstart/build/libs/war
                    destination: war
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments: 
                      - clean
                      - tests
                      - -p
                      - quickstart/                      
              artifacts:
                - build:
                    source: quickstart/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: quickstart/build/test-results/test/*.xml
                    destination: xml                    
              tabs:
                unit_test: html/index.html
      - Code_Quality:
          jobs:
            Sonarqube:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - sonarqube
                      - -p
                      - quickstart

  jr-java-webapp-quickstart-build:
    lock_behavior: lockOnFailure
    group: Application
    materials:
      repo:
        git: https://github.com/devops-at06/JR.git
        branch: master
    stages:
      - Commit:
          jobs:
            building:
              tasks:
                - exec:
                    command: ./webapp-quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "webapp-quickstart"
              artifacts:
                - build:
                    source: webapp-quickstart/build/libs/*.war
                    destination: war
      - Deploy:
          jobs:
            Application:
              tasks:
                - fetch:                    
                    stage: Commit
                    job: building
                    source: war/
                - exec:
                    command: ./webapp-quickstart/gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.109.116
                      - -Pwar_path=war
                      - -p
                      - webapp-quickstart
                      